name: Call Central Deploy

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: zhang-zixu/my-central-cicd/.github/workflows/universal-deploy.yml@main
    with:
      project_name: 'my-web-app'
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}